/*
* generated by Xtext
*/
package de.laegler.xdocker.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XDockerLangStandaloneSetup extends XDockerLangStandaloneSetupGenerated{

	public static void doSetup() {
		new XDockerLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

