/*
* generated by Xtext
*/
package de.laegler.xdocker.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XDockerLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/laegler/xdocker/lang/parser/antlr/internal/InternalXDockerLang.tokens");
	}
}
