/*
* generated by Xtext
*/
package de.laegler.xdocker.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.laegler.xdocker.lang.services.XDockerLangGrammarAccess;

public class XDockerLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XDockerLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.laegler.xdocker.lang.parser.antlr.internal.InternalXDockerLangParser createParser(XtextTokenStream stream) {
		return new de.laegler.xdocker.lang.parser.antlr.internal.InternalXDockerLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XDockerModel";
	}
	
	public XDockerLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XDockerLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
