/*
 * generated by Xtext
 */
package de.laegler.xdocker.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XDockerLangUiModule extends de.laegler.xdocker.lang.ui.AbstractXDockerLangUiModule {
	public XDockerLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
