/**
 * generated by Xtext
 */
package de.laegler.xdocker.lang.validation;

import de.laegler.xdocker.lang.validation.AbstractXDockerLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XDockerLangValidator extends AbstractXDockerLangValidator {
}
