/*
 * generated by Xtext
 */
package de.laegler.xdocker.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.laegler.xdocker.lang.ui.internal.XDockerLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XDockerLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XDockerLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XDockerLangActivator.getInstance().getInjector(XDockerLangActivator.DE_LAEGLER_XDOCKER_LANG_XDOCKERLANG);
	}
	
}
