/*
 * generated by Xtext
 */
package de.laegler.xdocker.lang.ui.contentassist

import de.laegler.xdocker.lang.ui.contentassist.AbstractXDockerLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XDockerLangProposalProvider extends AbstractXDockerLangProposalProvider {
}
