/*
* generated by Xtext
*/
package de.laegler.xdocker.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XDockerLangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.laegler.xdocker.lang.ui.internal.XDockerLangActivator.getInstance().getInjector("de.laegler.xdocker.lang.XDockerLang");
	}
	
}
